# Generated by Django 5.2.5 on 2025-08-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
    ]
